/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package insert_form;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import login.KoneksiDB;
import object.*;

/**
 *
 * @author ayyash
 */
public class Form_Supir extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    private Connection conn;
    private String tipe_aksi;
    private String id_supir;
    
    private void initDatabase(){
        try{
        conn = (Connection)KoneksiDB.configDB();
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }
    
    public Form_Supir() {
        initComponents();
        initDatabase();
        tipe_aksi = "Tambah Supir";
        lbl_judul.setText(tipe_aksi);
        btn_submit.setText("Tambah");
    }
    
    public Form_Supir(String id){
        initComponents();
        initDatabase();
        tipe_aksi = "Edit Supir";
        lbl_judul.setText(tipe_aksi);
        btn_submit.setText("Edit");
        id_supir = id;
        fillForm(getSupir(id_supir));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NoHPField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        NamaField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StatusField = new javax.swing.JComboBox<>();
        lbl_error = new javax.swing.JLabel();
        CusField = new javax.swing.JTextField();
        BiayaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_judul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("Form Supir");
        jPanel2.add(lbl_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nomor HP");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));

        NoHPField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoHPField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        NoHPField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NoHPFieldKeyReleased(evt);
            }
        });
        jPanel2.add(NoHPField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Biaya");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, -1));

        btn_back.setBackground(new java.awt.Color(102, 102, 255));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(102, 102, 255));
        btn_back.setText("Back");
        btn_back.setBorderPainted(false);
        btn_back.setContentAreaFilled(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        btn_submit.setBackground(new java.awt.Color(102, 102, 255));
        btn_submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Register");
        btn_submit.setBorderPainted(false);
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nama");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, -1));

        NamaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NamaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(NamaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Jumlah Customer");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Status");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        StatusField.setEditable(true);
        StatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Tersedia", "Tidak Tersedia" }));
        StatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusFieldActionPerformed(evt);
            }
        });
        jPanel2.add(StatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, 30));
        jPanel2.add(lbl_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 220, 20));

        CusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CusField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        CusField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CusFieldKeyReleased(evt);
            }
        });
        jPanel2.add(CusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, 30));

        BiayaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BiayaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        BiayaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BiayaFieldKeyReleased(evt);
            }
        });
        jPanel2.add(BiayaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 220, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        Validator v = new Validator();
        if(!v.isEmpty(NamaField)&&
                !v.isEmpty(BiayaField)&&
                !v.isEmpty(StatusField)&&
                !v.isEmpty(NoHPField)&&
                !v.isEmpty(CusField)
                ){
            if(tipe_aksi.equals("Tambah Supir")){
                insertSupir();
            }else if(tipe_aksi.equals("Edit Supir")){
                editSupir(id_supir);
            }else{
                System.out.println("No Type Inputted");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Form belum Komplit");
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void StatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusFieldActionPerformed

    private void CusFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CusFieldKeyReleased
        resetText(CusField);
    }//GEN-LAST:event_CusFieldKeyReleased

    private void BiayaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BiayaFieldKeyReleased
        resetText(BiayaField);
    }//GEN-LAST:event_BiayaFieldKeyReleased

    private void NoHPFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoHPFieldKeyReleased
       resetText(NoHPField);
    }//GEN-LAST:event_NoHPFieldKeyReleased
    
    private void resetText(JTextField txt){
        try {
            int angka = Integer.parseInt(txt.getText());
            lbl_error.setText("");
        } catch (NumberFormatException e) {
                lbl_error.setText("Tolong Masukan Angka");
                StringBuffer sb = new StringBuffer(txt.getText().toString());
                sb.deleteCharAt(sb.length()-1);
                txt.setText(sb+"");
        }
    }
    
    private void insertSupir(){
        try{
            Connection conn = (Connection)KoneksiDB.configDB();
            Statement state = conn.createStatement();
                
            Supir driver = new Supir();
            
//            pengguna.setHarga_sewa(Integer.valueOf(No.getText().toString()));
                
            driver.setNama(NamaField.getText().toString());
//            driver.setUsername(UsernameField.getText().toString());
//            driver.setPassword(PassField.getText().toString());
            driver.setNo_hp(NoHPField.getText().toString());
            driver.setBiaya(Integer.valueOf(BiayaField.getText().toString()));
            driver.setJml_cus(Integer.valueOf(CusField.getText().toString()));
            driver.setStatus(StatusField.getSelectedItem().toString());
                
            String query = "insert into supir(nama,no_telp,biaya,jml_cus,status) values "
                    + "("
                    + "'" + driver.getNama()+ "',"
                    + "'" + driver.getNo_hp()+ "',"
                    + "" + driver.getBiaya()+ ","
                    + "" + driver.getJml_cus()+ ","
                    + "'" + driver.getStatus()+ "'"
                    + ")";
                
            state.execute(query);
            JOptionPane.showMessageDialog(null, "Supir Berhasil Ditambah");
            this.dispose();
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Database Error");
        }
    }
    
    private void editSupir(String id){
        try{
            Statement state = conn.createStatement();
            
            Supir driver = new Supir();
                
            driver.setId_supir(Integer.valueOf(id));
            driver.setNama(NamaField.getText().toString());
            driver.setNo_hp(NoHPField.getText().toString());
            driver.setBiaya(Integer.valueOf(BiayaField.getText().toString()));
            driver.setJml_cus(Integer.valueOf(CusField.getText().toString()));
            driver.setStatus(StatusField.getSelectedItem().toString());
            
            String query = "update supir set "
                    + "nama = '" + driver.getNama() + "',"
                    + "no_telp = '"+ driver.getNo_hp()+ "',"
                    + "biaya = " + driver.getBiaya()+ ","
                    + "jml_cus = " + driver.getJml_cus()+ ","
                    + "status = '" + driver.getStatus()+ "'"
                    + " where id_supir = "+driver.getId_supir();
                
            state.executeUpdate(query);
            state.close();
            JOptionPane.showMessageDialog(null, "Supir Berhasil Diedit");
            this.dispose();
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Database Error");
        }
    }
    
    private Supir getSupir(String id){
        Supir driver = new Supir();
        try{
            Statement state = conn.createStatement();
            String query = "Select * from supir where id_supir = "+id;
            
            ResultSet rs = state.executeQuery(query);
            
            while(rs.next()){
                driver.setId_supir(rs.getInt("id_supir"));
                driver.setNama(rs.getString("nama"));
                driver.setStatus(rs.getString("status"));
                driver.setNo_hp(rs.getString("no_telp"));
                driver.setBiaya(rs.getInt("biaya"));
                driver.setJml_cus(rs.getInt("jml_cus"));
//                penggunabaru.set
            }
            state.close();
            rs.close();
            
        }catch(SQLException ex){
            System.out.println(ex);
        }
        return driver;
    }
    
    private void fillForm(Supir driver){
        NamaField.setText(driver.getNama());
        NoHPField.setText(driver.getNo_hp());
        BiayaField.setText(driver.getBiaya()+"");
        CusField.setText(driver.getJml_cus()+"");
        StatusField.setSelectedItem(driver.getStatus());
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Supir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Supir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Supir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Supir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Supir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BiayaField;
    private javax.swing.JTextField CusField;
    private javax.swing.JTextField NamaField;
    private javax.swing.JTextField NoHPField;
    private javax.swing.JComboBox<String> StatusField;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_judul;
    // End of variables declaration//GEN-END:variables
}
