/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ayyash
 */
public class Register extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    private void kosongin(){
        fName.setText("");
        rFemale.setSelected(false);
        rFemale.setSelected(false);
        fTelp.setText("");
        fAlamat.setText("");
        fUsername.setText("");
        fPassword.setText("");
        fPassword2.setText("");
        
    }
    private void kosonginpassword(){
        fPassword.setText("");
        fPassword2.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSex = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBackLogIn = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fPassword2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fTelp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fAlamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fPassword = new javax.swing.JPasswordField();
        rFemale = new javax.swing.JRadioButton();
        rMale1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fNoKtp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 450));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Username");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 70, -1));

        fUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 190, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Password");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, -1));

        btnBackLogIn.setBackground(new java.awt.Color(102, 102, 255));
        btnBackLogIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBackLogIn.setForeground(new java.awt.Color(102, 102, 255));
        btnBackLogIn.setText("Back");
        btnBackLogIn.setBorderPainted(false);
        btnBackLogIn.setContentAreaFilled(false);
        btnBackLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogInActionPerformed(evt);
            }
        });
        jPanel3.add(btnBackLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        btnRegister.setBackground(new java.awt.Color(102, 102, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Confirm password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, -1));

        fPassword2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fPassword2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fPassword2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        fName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Sex");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, -1));

        fTelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fTelp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fTelp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Alamat");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, -1));

        fAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fAlamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fAlamat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("No. Telp");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        fPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 190, 30));

        btnSex.add(rFemale);
        rFemale.setText("Female");
        rFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFemaleActionPerformed(evt);
            }
        });
        jPanel3.add(rFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        btnSex.add(rMale1);
        rMale1.setText("Male");
        rMale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMale1ActionPerformed(evt);
            }
        });
        jPanel3.add(rMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("No. Ktp");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 70, -1));

        fNoKtp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fNoKtp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fNoKtp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(fNoKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        String name=fName.getText();
//        String sex=ckbFemale.getActionCommand();
        String kelamin=sex;
        String no_telp=fTelp.getText();
        String alamat=fAlamat.getText();
        String username=fUsername.getText();
        String password=fPassword.getText();
        String password2=fPassword2.getText();
        String noktp=fNoKtp.getText();
        
        if (password.equals(password2)) {
            try {
            if(name.equals("")||no_telp.equals("")||username.equals("")||password.equals("")||password2.equals("")){
                JOptionPane.showMessageDialog(this, "Lengkapi data yang kosong.","Pesan",JOptionPane.ERROR_MESSAGE);
            }else{
            st=KoneksiDB.mysqlconfig.createStatement();
            st.executeUpdate("insert into penyewa(nama,username,password,gender,no_telp,alamat,no_ktp,saldo)"
                    + " values('"+name+"','"+username+"','"+password+"','"+kelamin+"','"+no_telp+"','"+alamat+"','"+noktp+"',0)");
            JOptionPane.showMessageDialog(rootPane, "Register berhasil.");
            this.setVisible(false);
            new Login().setVisible(true);
                 }
        }catch(Exception e){  
            JOptionPane.showMessageDialog(this, "Akun sudah ada.",
                    "Pesan",JOptionPane.WARNING_MESSAGE);
           kosongin();
        }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Passwords dont match.");
            kosonginpassword();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogInActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnBackLogInActionPerformed

    private void rFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFemaleActionPerformed
        // TODO add your handling code here:
        sex="Female";
    }//GEN-LAST:event_rFemaleActionPerformed

    private void rMale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMale1ActionPerformed
        // TODO add your handling code here:
        sex="Male";
    }//GEN-LAST:event_rMale1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLogIn;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup btnSex;
    private javax.swing.JTextField fAlamat;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fNoKtp;
    private javax.swing.JPasswordField fPassword;
    private javax.swing.JPasswordField fPassword2;
    private javax.swing.JTextField fTelp;
    private javax.swing.JTextField fUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale1;
    // End of variables declaration//GEN-END:variables
private String sex;
}

